"""Make id_uuid non-nullable

Revision ID: b7a39c2d5e1e
Revises: 5c7d34163ef0
Create Date: 2022-04-02 18:13:31.219823

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7a39c2d5e1e'
down_revision = '5c7d34163ef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('allotment', 'id_uuid',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('allotment', 'id_uuid',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###
