""" Renames uuid to id_uuid and adds as_uuid to column type

Revision ID: 5c7d34163ef0
Revises: e503739d6d04
Create Date: 2022-04-02 17:40:59.611463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c7d34163ef0'
down_revision = 'e503739d6d04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allotment', sa.Column('id_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_column('allotment', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allotment', sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_column('allotment', 'id_uuid')
    # ### end Alembic commands ###
